<?php

/**
 * @file
 * Install, update and uninstall functions for the Field Collection Table module.
 */

/**
 * Implements hook_uninstall().
 */
function field_collection_table_uninstall() {
  config_clear('field_collection_table.settings', 'field_collection_table_format_form');
  config_clear('field_collection_table.settings', 'field_collection_table_hide_empty');
}

// TODO The old hook_update_N functions cannot be applied to Backdrop.
function field_collection_table_update_7001() { }
